/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author aluno.fatene
 */
public class TelaPrincipal extends javax.swing.JFrame {

    //Telas
    TelaCadAmbulatorio tCA;
    TelaCadPaciente tCP;
    TelaCadFunc tCF;

    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        menu_relconsultas = new javax.swing.JMenuItem();
        menu_relmedicos = new javax.swing.JMenuItem();
        menu_relfunc = new javax.swing.JMenuItem();
        menu_relambulatorio = new javax.swing.JMenuItem();
        menu_relpacientes = new javax.swing.JMenuItem();
        mainDesktop = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_cadfunc = new javax.swing.JMenuItem();
        menu_cadambu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_cadpaciente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_consultas = new javax.swing.JMenuItem();

        jMenu2.setText("Relatórios");

        menu_relconsultas.setText("Consultas");
        jMenu2.add(menu_relconsultas);

        menu_relmedicos.setText("Medicos");
        menu_relmedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relmedicosActionPerformed(evt);
            }
        });
        jMenu2.add(menu_relmedicos);

        menu_relfunc.setText("Funcionarios");
        jMenu2.add(menu_relfunc);

        menu_relambulatorio.setText("Ambulatorios");
        jMenu2.add(menu_relambulatorio);

        menu_relpacientes.setText("Pacientes");
        jMenu2.add(menu_relpacientes);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_whatsapp_24px_4.png"))); // NOI18N
        jLabel1.setText("  ");
        jToolBar1.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_gmail_24px.png"))); // NOI18N
        jLabel2.setText("  ");
        jToolBar1.add(jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_instagram_new_24px.png"))); // NOI18N
        jLabel3.setText("  ");
        jToolBar1.add(jLabel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_facebook_24px.png"))); // NOI18N
        jLabel4.setText("  ");
        jToolBar1.add(jLabel4);

        jMenu1.setText("Cadastro");

        menu_cadfunc.setText("Funcionário");
        menu_cadfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadfuncActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cadfunc);

        menu_cadambu.setText("Ambulatório");
        menu_cadambu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadambuActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cadambu);
        jMenu1.add(jSeparator1);

        menu_cadpaciente.setText("Paciente");
        menu_cadpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadpacienteActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cadpaciente);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Atendimento");

        menu_consultas.setText("Consulta");
        menu_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consultasActionPerformed(evt);
            }
        });
        jMenu3.add(menu_consultas);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktop)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainDesktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_cadfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadfuncActionPerformed
        if(tCF == null){
            tCF = new TelaCadFunc();
            tCF.setVisible(true);
            mainDesktop.add(tCF);
        }
    }//GEN-LAST:event_menu_cadfuncActionPerformed

    private void menu_cadambuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadambuActionPerformed
        if(tCA == null){
            tCA = new TelaCadAmbulatorio();
            tCA.setVisible(true);
            mainDesktop.add(tCA);
        }
    }//GEN-LAST:event_menu_cadambuActionPerformed

    private void menu_cadpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadpacienteActionPerformed
        if(tCP == null){
            tCP = new TelaCadPaciente();
            tCP.setVisible(true);
            mainDesktop.add(tCP);
        }
    }//GEN-LAST:event_menu_cadpacienteActionPerformed

    private void menu_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consultasActionPerformed
        
    }//GEN-LAST:event_menu_consultasActionPerformed

    private void menu_relmedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relmedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_relmedicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JMenuItem menu_cadambu;
    private javax.swing.JMenuItem menu_cadfunc;
    private javax.swing.JMenuItem menu_cadpaciente;
    private javax.swing.JMenuItem menu_consultas;
    private javax.swing.JMenuItem menu_relambulatorio;
    private javax.swing.JMenuItem menu_relconsultas;
    private javax.swing.JMenuItem menu_relfunc;
    private javax.swing.JMenuItem menu_relmedicos;
    private javax.swing.JMenuItem menu_relpacientes;
    // End of variables declaration//GEN-END:variables
}
